
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdjfqdpoesjvbluffwzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkamZxZHBvZXNqdmJsdWZmd3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjUwMzMsImV4cCI6MjA1ODYwMTAzM30.EZY4vaHzt11hJhV2MR8S1c9PJHhZpbv0NZIdBm24QZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add custom types for tables not in the auto-generated types
declare module './types' {
  interface Database {
    public: {
      Tables: {
        appearance_settings: {
          Row: {
            id: number;
            logo_url: string | null;
            primary_color: string;
            secondary_color: string;
            accent_color: string;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: number;
            logo_url?: string | null;
            primary_color: string;
            secondary_color: string;
            accent_color: string;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: number;
            logo_url?: string | null;
            primary_color?: string;
            secondary_color?: string;
            accent_color?: string;
            created_at?: string;
            updated_at?: string;
          };
        }
      }
    }
  }
}
